version: "3.2"

services:
  backend:
    build: .
    volumes:
      - type: bind
        source: ./
        target: /code
    ports:
     - "5000:5000"

  frontend:
    image: nginx:1.15.8-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    ports:
      - 80:80
